name: Deploy Storybook to GitHub Pages

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev @storybook/nextjs @storybook/react @storybook/addon-essentials

      - name: Install Storybook if not present
        run: npm storybook@latest init --yes --builder @storybook/builder-webpack5
        continue-on-error: true
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          branch: gh-pages
          clean: true